# GitHub Actions workflow for Homebridge UniFi AP Lights plugin
# Runs build, lint, and tests on supported Node.js versions
# Also runs a Homebridge v1 and v2 compatibility smoke test

name: Build, Lint, Test, and Homebridge Compatibility

on: [push, pull_request]

jobs:
  # Main build, lint, and test job for supported Node.js versions
  build-lint-test:
    name: Build, Lint, and Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x] # Only test supported Node.js versions
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint the project
        run: npm run lint
      - name: Build the project
        run: npm run build
        env:
          CI: true
      - name: Run tests # Run all unit and integration tests
        run: |
          npm test || npx vitest run
